/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { EWS } from "./contracts/EWS.sol/EWS";
export { EWS__factory } from "./factories/contracts/EWS.sol/EWS__factory";
export type { IDC } from "./contracts/EWS.sol/IDC";
export { IDC__factory } from "./factories/contracts/EWS.sol/IDC__factory";
